-- T) a) Listar los clientes compraron TODOS los articulos (1 fila - cliente 304)
--    b) Listar los clientes que en Junio compraron TODOS los articulos del rubro
--       "Tornillos". (2 filas - clientes 160 - 304)
/*SELECT F.CLIENTE
FROM DETALLES D INNER JOIN FACTURAS F ON F.NROFACTURA=D.NROFACTURA
GROUP BY F.CLIENTE
HAVING COUNT(*)=(SELECT COUNT(*) FROM ARTICULOS WHERE NROARTIC IS NOT NULL)*/

SELECT F.CLIENTE
FROM DETALLES D INNER JOIN FACTURAS F ON F.NROFACTURA=D.NROFACTURA
WHERE (FECHA BETWEEN '2010-6-1' AND '2010-6-30') AND NOT EXISTS(
		SELECT *
		FROM ARTICULOS A INNER JOIN RUBROS R ON A.RUBRO=R.COD_RUBRO
		WHERE R.DESCRIPCION ILIKE 'TORNILLOS' AND NOT EXISTS(
		 	SELECT *
			FROM DETALLES D1 INNER JOIN FACTURAS F1 ON F1.NROFACTURA=D1.NROFACTURA
			WHERE (FECHA BETWEEN '2010-6-1' AND '2010-6-30') 
				AND F1.CLIENTE=F.CLIENTE AND A.NROARTIC=D1.ARTICULO))

GROUP BY F.CLIENTE