-- 5) Listar las localidades que vendieron mas de que lo que se le facturo al cliente 179
SELECT C.LOCALIDAD
FROM CLIENTES C, FACTURAS F, DETALLES D
WHERE C.NROCLI=F.CLIENTE AND F.NROFACTURA=D.NROFACTURA 

GROUP BY C.LOCALIDAD
HAVING SUM(D.PRECIOUNI*CANTIDAD)>(SELECT SUM(PRECIOUNI*CANTIDAD) 
		FROM FACTURAS F,DETALLES D 
		WHERE F.NROFACTURA=D.NROFACTURA AND F.CLIENTE=179)