-- Y) Listar los clientes de 'Capital Federal' que NO compraron articulos del
--    rubro 'Articulos de Electricidad' durante mayo de a�o 2010.
--    Ordenar los datos en forma descendente por nombre y apellido.
--    (Rsta: 10 filas)
SELECT C.*, COUNT(*) FACTURAS
FROM CLIENTES C INNER JOIN FACTURAS F ON F.CLIENTE=C.NROCLI
WHERE LOCALIDAD ILIKE 'CAPITAL FEDERAL' AND NOT EXISTS(
	SELECT F1.CLIENTE
	FROM FACTURAS F1, DETALLES D
	WHERE F1.NROFACTURA=D.NROFACTURA AND F1.CLIENTE=F.CLIENTE
	AND (F1.FECHA BETWEEN '2010-5-1' AND '2010-5-31') 
	AND EXISTS(
		SELECT D1.NROFACTURA
		FROM ARTICULOS A, RUBROS R, DETALLES D1
		WHERE A.RUBRO=R.COD_RUBRO AND A.NROARTIC=D1.ARTICULO AND D.NROFACTURA=D1.NROFACTURA 
		AND R.DESCRIPCION ILIKE 'ARTICULOS DE ELECTRICIDAD'))

GROUP BY C.NROCLI
ORDER BY C.NYAPE
