-- N) Obtener el promedio del importe diario de las ventas del mes de mayo del 2010.
SELECT AVG(CANTIDAD*PRECIOUNI) PROMEDIO
FROM DETALLES D INNER JOIN FACTURAS F ON D.NROFACTURA=F.NROFACTURA
WHERE FECHA BETWEEN '2010-5-1' AND '2010-5-31'

GROUP BY FECHA