-- h) Obtener la fecha en la q se facturo mas
SELECT SUM(CANTIDAD * PRECIOUNI) PRECIOTOTAL, CAST (F.FECHA AS DATE)
FROM FACTURAS F INNER JOIN DETALLES D ON D.NROFACTURA = F.NROFACTURA

GROUP BY F.FECHA
HAVING SUM(CANTIDAD * PRECIOUNI) >= ALL(
	SELECT SUM(CANTIDAD * PRECIOUNI) PRECIOTOTAL
	FROM FACTURAS F,DETALLES D
	WHERE  F.NROFACTURA=D.NROFACTURA
	GROUP BY FECHA)